version: '3.8'
services:
  redis-server:
    image: 'redis'
    #restart: always
  node-app:
    restart: always
    #restart: on-failure
    #restart: unless-stopped
    build: .
    ports:
      - '4001:8081'
